name = "rag"
main = "src/index.ts"
compatibility_date = "2024-10-28"

[ai]
binding = "AI"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DATABASE"  # Ensure the binding name matches the code
database_name = "RUSSTCORP-AI-DATABASE"
database_id = "28b28058-1a2c-4dfa-821a-f633bff5d5e9"

[[vectorize]]
binding = "VECTORIZE"
index_name = "russtcorp-ai-vector-index"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"

[[kv_namespaces]]
binding = "USERS_KV"
id = "5218b724e0304713bcb7c036f576b433"

[durable_objects]
bindings = [
  { name = "SESSIONS_DO", class_name = "SessionDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionDO"]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
# Remove or comment out the JWT_SECRET line since we're generating it dynamically
# JWT_SECRET = "your-secret-key-here"

compatibility_flags = ["nodejs_compat"]
